// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scoutingdata.proto

package org.stormgears.stormgearsscoutingv20.data;

public final class Scoutingdata {
  private Scoutingdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string password = 1;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 1;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string eventCode = 2;</code>
     */
    java.lang.String getEventCode();
    /**
     * <code>optional string eventCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getEventCodeBytes();

    /**
     * <code>optional string scoutType = 3;</code>
     */
    java.lang.String getScoutType();
    /**
     * <code>optional string scoutType = 3;</code>
     */
    com.google.protobuf.ByteString
        getScoutTypeBytes();

    /**
     * <code>optional int32 teamNumber = 4;</code>
     */
    int getTeamNumber();

    /**
     * <code>optional int32 m_matchNumber = 5;</code>
     */
    int getMMatchNumber();

    /**
     * <code>optional string m_matchType = 6;</code>
     */
    java.lang.String getMMatchType();
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    com.google.protobuf.ByteString
        getMMatchTypeBytes();

    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    java.lang.String getMAllianceColor();
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    com.google.protobuf.ByteString
        getMAllianceColorBytes();

    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    java.lang.String getMAutoGearStrategy();
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    com.google.protobuf.ByteString
        getMAutoGearStrategyBytes();

    /**
     * <code>optional int32 m_auto_lowShots = 9;</code>
     */
    int getMAutoLowShots();

    /**
     * <code>optional int32 m_auto_highShots = 10;</code>
     */
    int getMAutoHighShots();

    /**
     * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
     */
    int getMAutoPercentShotsMissed();

    /**
     * <code>optional bool m_auto_crossedBaseline = 12;</code>
     */
    boolean getMAutoCrossedBaseline();

    /**
     * <code>optional int32 m_tele_gearsPlaced = 13;</code>
     */
    int getMTeleGearsPlaced();

    /**
     * <code>optional int32 m_tele_lowShots = 14;</code>
     */
    int getMTeleLowShots();

    /**
     * <code>optional int32 m_tele_highShots = 15;</code>
     */
    int getMTeleHighShots();

    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    java.lang.String getMTelePercentShotsMissed();
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    com.google.protobuf.ByteString
        getMTelePercentShotsMissedBytes();

    /**
     * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
     */
    int getMTeleRotorsSpinning();

    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    java.lang.String getMTeleBallRetrievalMethod();
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    com.google.protobuf.ByteString
        getMTeleBallRetrievalMethodBytes();

    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    java.lang.String getMTeleRobotClimbStatus();
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    com.google.protobuf.ByteString
        getMTeleRobotClimbStatusBytes();

    /**
     * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
     */
    boolean getMTeleAirshipReadyForTakeoff();

    /**
     * <code>optional string m_comments = 21;</code>
     */
    java.lang.String getMComments();
    /**
     * <code>optional string m_comments = 21;</code>
     */
    com.google.protobuf.ByteString
        getMCommentsBytes();

    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    java.lang.String getMOverallStrategy();
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    com.google.protobuf.ByteString
        getMOverallStrategyBytes();

    /**
     * <code>optional int32 m_redMatchPoints = 23;</code>
     */
    int getMRedMatchPoints();

    /**
     * <code>optional int32 m_blueMatchPoints = 24;</code>
     */
    int getMBlueMatchPoints();

    /**
     * <code>optional int32 m_redRankingPoints = 25;</code>
     */
    int getMRedRankingPoints();

    /**
     * <code>optional int32 m_blueRankingPoints = 26;</code>
     */
    int getMBlueRankingPoints();

    /**
     * <code>optional string p_teamName = 27;</code>
     */
    java.lang.String getPTeamName();
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    com.google.protobuf.ByteString
        getPTeamNameBytes();

    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    java.lang.String getPDrivetraintype();
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    com.google.protobuf.ByteString
        getPDrivetraintypeBytes();

    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    java.lang.String getPMatchStrategy();
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    com.google.protobuf.ByteString
        getPMatchStrategyBytes();

    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    java.lang.String getPRobotStrengths();
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    com.google.protobuf.ByteString
        getPRobotStrengthsBytes();

    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    java.lang.String getPRobotWeaknesses();
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    com.google.protobuf.ByteString
        getPRobotWeaknessesBytes();

    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    java.lang.String getPOtherComments();
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    com.google.protobuf.ByteString
        getPOtherCommentsBytes();
  }
  /**
   * Protobuf type {@code Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageLite<
          Event, Event.Builder> implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
    private Event() {
      password_ = "";
      eventCode_ = "";
      scoutType_ = "";
      mMatchType_ = "";
      mAllianceColor_ = "";
      mAutoGearStrategy_ = "";
      mTelePercentShotsMissed_ = "";
      mTeleBallRetrievalMethod_ = "";
      mTeleRobotClimbStatus_ = "";
      mComments_ = "";
      mOverallStrategy_ = "";
      pTeamName_ = "";
      pDrivetraintype_ = "";
      pMatchStrategy_ = "";
      pRobotStrengths_ = "";
      pRobotWeaknesses_ = "";
      pOtherComments_ = "";
    }
    public static final int PASSWORD_FIELD_NUMBER = 1;
    private java.lang.String password_;
    /**
     * <code>optional string password = 1;</code>
     */
    public java.lang.String getPassword() {
      return password_;
    }
    /**
     * <code>optional string password = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>optional string password = 1;</code>
     */
    private void setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
    }
    /**
     * <code>optional string password = 1;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>optional string password = 1;</code>
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value.toStringUtf8();
    }

    public static final int EVENTCODE_FIELD_NUMBER = 2;
    private java.lang.String eventCode_;
    /**
     * <code>optional string eventCode = 2;</code>
     */
    public java.lang.String getEventCode() {
      return eventCode_;
    }
    /**
     * <code>optional string eventCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEventCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(eventCode_);
    }
    /**
     * <code>optional string eventCode = 2;</code>
     */
    private void setEventCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventCode_ = value;
    }
    /**
     * <code>optional string eventCode = 2;</code>
     */
    private void clearEventCode() {
      
      eventCode_ = getDefaultInstance().getEventCode();
    }
    /**
     * <code>optional string eventCode = 2;</code>
     */
    private void setEventCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventCode_ = value.toStringUtf8();
    }

    public static final int SCOUTTYPE_FIELD_NUMBER = 3;
    private java.lang.String scoutType_;
    /**
     * <code>optional string scoutType = 3;</code>
     */
    public java.lang.String getScoutType() {
      return scoutType_;
    }
    /**
     * <code>optional string scoutType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getScoutTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(scoutType_);
    }
    /**
     * <code>optional string scoutType = 3;</code>
     */
    private void setScoutType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scoutType_ = value;
    }
    /**
     * <code>optional string scoutType = 3;</code>
     */
    private void clearScoutType() {
      
      scoutType_ = getDefaultInstance().getScoutType();
    }
    /**
     * <code>optional string scoutType = 3;</code>
     */
    private void setScoutTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scoutType_ = value.toStringUtf8();
    }

    public static final int TEAMNUMBER_FIELD_NUMBER = 4;
    private int teamNumber_;
    /**
     * <code>optional int32 teamNumber = 4;</code>
     */
    public int getTeamNumber() {
      return teamNumber_;
    }
    /**
     * <code>optional int32 teamNumber = 4;</code>
     */
    private void setTeamNumber(int value) {
      
      teamNumber_ = value;
    }
    /**
     * <code>optional int32 teamNumber = 4;</code>
     */
    private void clearTeamNumber() {
      
      teamNumber_ = 0;
    }

    public static final int M_MATCHNUMBER_FIELD_NUMBER = 5;
    private int mMatchNumber_;
    /**
     * <code>optional int32 m_matchNumber = 5;</code>
     */
    public int getMMatchNumber() {
      return mMatchNumber_;
    }
    /**
     * <code>optional int32 m_matchNumber = 5;</code>
     */
    private void setMMatchNumber(int value) {
      
      mMatchNumber_ = value;
    }
    /**
     * <code>optional int32 m_matchNumber = 5;</code>
     */
    private void clearMMatchNumber() {
      
      mMatchNumber_ = 0;
    }

    public static final int M_MATCHTYPE_FIELD_NUMBER = 6;
    private java.lang.String mMatchType_;
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    public java.lang.String getMMatchType() {
      return mMatchType_;
    }
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMMatchTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mMatchType_);
    }
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    private void setMMatchType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mMatchType_ = value;
    }
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    private void clearMMatchType() {
      
      mMatchType_ = getDefaultInstance().getMMatchType();
    }
    /**
     * <code>optional string m_matchType = 6;</code>
     */
    private void setMMatchTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mMatchType_ = value.toStringUtf8();
    }

    public static final int M_ALLIANCECOLOR_FIELD_NUMBER = 7;
    private java.lang.String mAllianceColor_;
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    public java.lang.String getMAllianceColor() {
      return mAllianceColor_;
    }
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMAllianceColorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mAllianceColor_);
    }
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    private void setMAllianceColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mAllianceColor_ = value;
    }
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    private void clearMAllianceColor() {
      
      mAllianceColor_ = getDefaultInstance().getMAllianceColor();
    }
    /**
     * <code>optional string m_allianceColor = 7;</code>
     */
    private void setMAllianceColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mAllianceColor_ = value.toStringUtf8();
    }

    public static final int M_AUTO_GEARSTRATEGY_FIELD_NUMBER = 8;
    private java.lang.String mAutoGearStrategy_;
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    public java.lang.String getMAutoGearStrategy() {
      return mAutoGearStrategy_;
    }
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMAutoGearStrategyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mAutoGearStrategy_);
    }
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    private void setMAutoGearStrategy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mAutoGearStrategy_ = value;
    }
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    private void clearMAutoGearStrategy() {
      
      mAutoGearStrategy_ = getDefaultInstance().getMAutoGearStrategy();
    }
    /**
     * <code>optional string m_auto_gearStrategy = 8;</code>
     */
    private void setMAutoGearStrategyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mAutoGearStrategy_ = value.toStringUtf8();
    }

    public static final int M_AUTO_LOWSHOTS_FIELD_NUMBER = 9;
    private int mAutoLowShots_;
    /**
     * <code>optional int32 m_auto_lowShots = 9;</code>
     */
    public int getMAutoLowShots() {
      return mAutoLowShots_;
    }
    /**
     * <code>optional int32 m_auto_lowShots = 9;</code>
     */
    private void setMAutoLowShots(int value) {
      
      mAutoLowShots_ = value;
    }
    /**
     * <code>optional int32 m_auto_lowShots = 9;</code>
     */
    private void clearMAutoLowShots() {
      
      mAutoLowShots_ = 0;
    }

    public static final int M_AUTO_HIGHSHOTS_FIELD_NUMBER = 10;
    private int mAutoHighShots_;
    /**
     * <code>optional int32 m_auto_highShots = 10;</code>
     */
    public int getMAutoHighShots() {
      return mAutoHighShots_;
    }
    /**
     * <code>optional int32 m_auto_highShots = 10;</code>
     */
    private void setMAutoHighShots(int value) {
      
      mAutoHighShots_ = value;
    }
    /**
     * <code>optional int32 m_auto_highShots = 10;</code>
     */
    private void clearMAutoHighShots() {
      
      mAutoHighShots_ = 0;
    }

    public static final int M_AUTO_PERCENTSHOTSMISSED_FIELD_NUMBER = 11;
    private int mAutoPercentShotsMissed_;
    /**
     * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
     */
    public int getMAutoPercentShotsMissed() {
      return mAutoPercentShotsMissed_;
    }
    /**
     * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
     */
    private void setMAutoPercentShotsMissed(int value) {
      
      mAutoPercentShotsMissed_ = value;
    }
    /**
     * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
     */
    private void clearMAutoPercentShotsMissed() {
      
      mAutoPercentShotsMissed_ = 0;
    }

    public static final int M_AUTO_CROSSEDBASELINE_FIELD_NUMBER = 12;
    private boolean mAutoCrossedBaseline_;
    /**
     * <code>optional bool m_auto_crossedBaseline = 12;</code>
     */
    public boolean getMAutoCrossedBaseline() {
      return mAutoCrossedBaseline_;
    }
    /**
     * <code>optional bool m_auto_crossedBaseline = 12;</code>
     */
    private void setMAutoCrossedBaseline(boolean value) {
      
      mAutoCrossedBaseline_ = value;
    }
    /**
     * <code>optional bool m_auto_crossedBaseline = 12;</code>
     */
    private void clearMAutoCrossedBaseline() {
      
      mAutoCrossedBaseline_ = false;
    }

    public static final int M_TELE_GEARSPLACED_FIELD_NUMBER = 13;
    private int mTeleGearsPlaced_;
    /**
     * <code>optional int32 m_tele_gearsPlaced = 13;</code>
     */
    public int getMTeleGearsPlaced() {
      return mTeleGearsPlaced_;
    }
    /**
     * <code>optional int32 m_tele_gearsPlaced = 13;</code>
     */
    private void setMTeleGearsPlaced(int value) {
      
      mTeleGearsPlaced_ = value;
    }
    /**
     * <code>optional int32 m_tele_gearsPlaced = 13;</code>
     */
    private void clearMTeleGearsPlaced() {
      
      mTeleGearsPlaced_ = 0;
    }

    public static final int M_TELE_LOWSHOTS_FIELD_NUMBER = 14;
    private int mTeleLowShots_;
    /**
     * <code>optional int32 m_tele_lowShots = 14;</code>
     */
    public int getMTeleLowShots() {
      return mTeleLowShots_;
    }
    /**
     * <code>optional int32 m_tele_lowShots = 14;</code>
     */
    private void setMTeleLowShots(int value) {
      
      mTeleLowShots_ = value;
    }
    /**
     * <code>optional int32 m_tele_lowShots = 14;</code>
     */
    private void clearMTeleLowShots() {
      
      mTeleLowShots_ = 0;
    }

    public static final int M_TELE_HIGHSHOTS_FIELD_NUMBER = 15;
    private int mTeleHighShots_;
    /**
     * <code>optional int32 m_tele_highShots = 15;</code>
     */
    public int getMTeleHighShots() {
      return mTeleHighShots_;
    }
    /**
     * <code>optional int32 m_tele_highShots = 15;</code>
     */
    private void setMTeleHighShots(int value) {
      
      mTeleHighShots_ = value;
    }
    /**
     * <code>optional int32 m_tele_highShots = 15;</code>
     */
    private void clearMTeleHighShots() {
      
      mTeleHighShots_ = 0;
    }

    public static final int M_TELE_PERCENTSHOTSMISSED_FIELD_NUMBER = 16;
    private java.lang.String mTelePercentShotsMissed_;
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    public java.lang.String getMTelePercentShotsMissed() {
      return mTelePercentShotsMissed_;
    }
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    public com.google.protobuf.ByteString
        getMTelePercentShotsMissedBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mTelePercentShotsMissed_);
    }
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    private void setMTelePercentShotsMissed(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mTelePercentShotsMissed_ = value;
    }
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    private void clearMTelePercentShotsMissed() {
      
      mTelePercentShotsMissed_ = getDefaultInstance().getMTelePercentShotsMissed();
    }
    /**
     * <code>optional string m_tele_percentShotsMissed = 16;</code>
     */
    private void setMTelePercentShotsMissedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mTelePercentShotsMissed_ = value.toStringUtf8();
    }

    public static final int M_TELE_ROTORSSPINNING_FIELD_NUMBER = 17;
    private int mTeleRotorsSpinning_;
    /**
     * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
     */
    public int getMTeleRotorsSpinning() {
      return mTeleRotorsSpinning_;
    }
    /**
     * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
     */
    private void setMTeleRotorsSpinning(int value) {
      
      mTeleRotorsSpinning_ = value;
    }
    /**
     * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
     */
    private void clearMTeleRotorsSpinning() {
      
      mTeleRotorsSpinning_ = 0;
    }

    public static final int M_TELE_BALLRETRIEVALMETHOD_FIELD_NUMBER = 18;
    private java.lang.String mTeleBallRetrievalMethod_;
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    public java.lang.String getMTeleBallRetrievalMethod() {
      return mTeleBallRetrievalMethod_;
    }
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    public com.google.protobuf.ByteString
        getMTeleBallRetrievalMethodBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mTeleBallRetrievalMethod_);
    }
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    private void setMTeleBallRetrievalMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mTeleBallRetrievalMethod_ = value;
    }
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    private void clearMTeleBallRetrievalMethod() {
      
      mTeleBallRetrievalMethod_ = getDefaultInstance().getMTeleBallRetrievalMethod();
    }
    /**
     * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
     */
    private void setMTeleBallRetrievalMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mTeleBallRetrievalMethod_ = value.toStringUtf8();
    }

    public static final int M_TELE_ROBOTCLIMBSTATUS_FIELD_NUMBER = 19;
    private java.lang.String mTeleRobotClimbStatus_;
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    public java.lang.String getMTeleRobotClimbStatus() {
      return mTeleRobotClimbStatus_;
    }
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    public com.google.protobuf.ByteString
        getMTeleRobotClimbStatusBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mTeleRobotClimbStatus_);
    }
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    private void setMTeleRobotClimbStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mTeleRobotClimbStatus_ = value;
    }
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    private void clearMTeleRobotClimbStatus() {
      
      mTeleRobotClimbStatus_ = getDefaultInstance().getMTeleRobotClimbStatus();
    }
    /**
     * <code>optional string m_tele_robotClimbStatus = 19;</code>
     */
    private void setMTeleRobotClimbStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mTeleRobotClimbStatus_ = value.toStringUtf8();
    }

    public static final int M_TELE_AIRSHIPREADYFORTAKEOFF_FIELD_NUMBER = 20;
    private boolean mTeleAirshipReadyForTakeoff_;
    /**
     * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
     */
    public boolean getMTeleAirshipReadyForTakeoff() {
      return mTeleAirshipReadyForTakeoff_;
    }
    /**
     * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
     */
    private void setMTeleAirshipReadyForTakeoff(boolean value) {
      
      mTeleAirshipReadyForTakeoff_ = value;
    }
    /**
     * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
     */
    private void clearMTeleAirshipReadyForTakeoff() {
      
      mTeleAirshipReadyForTakeoff_ = false;
    }

    public static final int M_COMMENTS_FIELD_NUMBER = 21;
    private java.lang.String mComments_;
    /**
     * <code>optional string m_comments = 21;</code>
     */
    public java.lang.String getMComments() {
      return mComments_;
    }
    /**
     * <code>optional string m_comments = 21;</code>
     */
    public com.google.protobuf.ByteString
        getMCommentsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mComments_);
    }
    /**
     * <code>optional string m_comments = 21;</code>
     */
    private void setMComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mComments_ = value;
    }
    /**
     * <code>optional string m_comments = 21;</code>
     */
    private void clearMComments() {
      
      mComments_ = getDefaultInstance().getMComments();
    }
    /**
     * <code>optional string m_comments = 21;</code>
     */
    private void setMCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mComments_ = value.toStringUtf8();
    }

    public static final int M_OVERALLSTRATEGY_FIELD_NUMBER = 22;
    private java.lang.String mOverallStrategy_;
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    public java.lang.String getMOverallStrategy() {
      return mOverallStrategy_;
    }
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    public com.google.protobuf.ByteString
        getMOverallStrategyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mOverallStrategy_);
    }
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    private void setMOverallStrategy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mOverallStrategy_ = value;
    }
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    private void clearMOverallStrategy() {
      
      mOverallStrategy_ = getDefaultInstance().getMOverallStrategy();
    }
    /**
     * <code>optional string m_overallStrategy = 22;</code>
     */
    private void setMOverallStrategyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mOverallStrategy_ = value.toStringUtf8();
    }

    public static final int M_REDMATCHPOINTS_FIELD_NUMBER = 23;
    private int mRedMatchPoints_;
    /**
     * <code>optional int32 m_redMatchPoints = 23;</code>
     */
    public int getMRedMatchPoints() {
      return mRedMatchPoints_;
    }
    /**
     * <code>optional int32 m_redMatchPoints = 23;</code>
     */
    private void setMRedMatchPoints(int value) {
      
      mRedMatchPoints_ = value;
    }
    /**
     * <code>optional int32 m_redMatchPoints = 23;</code>
     */
    private void clearMRedMatchPoints() {
      
      mRedMatchPoints_ = 0;
    }

    public static final int M_BLUEMATCHPOINTS_FIELD_NUMBER = 24;
    private int mBlueMatchPoints_;
    /**
     * <code>optional int32 m_blueMatchPoints = 24;</code>
     */
    public int getMBlueMatchPoints() {
      return mBlueMatchPoints_;
    }
    /**
     * <code>optional int32 m_blueMatchPoints = 24;</code>
     */
    private void setMBlueMatchPoints(int value) {
      
      mBlueMatchPoints_ = value;
    }
    /**
     * <code>optional int32 m_blueMatchPoints = 24;</code>
     */
    private void clearMBlueMatchPoints() {
      
      mBlueMatchPoints_ = 0;
    }

    public static final int M_REDRANKINGPOINTS_FIELD_NUMBER = 25;
    private int mRedRankingPoints_;
    /**
     * <code>optional int32 m_redRankingPoints = 25;</code>
     */
    public int getMRedRankingPoints() {
      return mRedRankingPoints_;
    }
    /**
     * <code>optional int32 m_redRankingPoints = 25;</code>
     */
    private void setMRedRankingPoints(int value) {
      
      mRedRankingPoints_ = value;
    }
    /**
     * <code>optional int32 m_redRankingPoints = 25;</code>
     */
    private void clearMRedRankingPoints() {
      
      mRedRankingPoints_ = 0;
    }

    public static final int M_BLUERANKINGPOINTS_FIELD_NUMBER = 26;
    private int mBlueRankingPoints_;
    /**
     * <code>optional int32 m_blueRankingPoints = 26;</code>
     */
    public int getMBlueRankingPoints() {
      return mBlueRankingPoints_;
    }
    /**
     * <code>optional int32 m_blueRankingPoints = 26;</code>
     */
    private void setMBlueRankingPoints(int value) {
      
      mBlueRankingPoints_ = value;
    }
    /**
     * <code>optional int32 m_blueRankingPoints = 26;</code>
     */
    private void clearMBlueRankingPoints() {
      
      mBlueRankingPoints_ = 0;
    }

    public static final int P_TEAMNAME_FIELD_NUMBER = 27;
    private java.lang.String pTeamName_;
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    public java.lang.String getPTeamName() {
      return pTeamName_;
    }
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    public com.google.protobuf.ByteString
        getPTeamNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pTeamName_);
    }
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    private void setPTeamName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pTeamName_ = value;
    }
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    private void clearPTeamName() {
      
      pTeamName_ = getDefaultInstance().getPTeamName();
    }
    /**
     * <code>optional string p_teamName = 27;</code>
     */
    private void setPTeamNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pTeamName_ = value.toStringUtf8();
    }

    public static final int P_DRIVETRAINTYPE_FIELD_NUMBER = 28;
    private java.lang.String pDrivetraintype_;
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    public java.lang.String getPDrivetraintype() {
      return pDrivetraintype_;
    }
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    public com.google.protobuf.ByteString
        getPDrivetraintypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pDrivetraintype_);
    }
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    private void setPDrivetraintype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pDrivetraintype_ = value;
    }
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    private void clearPDrivetraintype() {
      
      pDrivetraintype_ = getDefaultInstance().getPDrivetraintype();
    }
    /**
     * <code>optional string p_drivetraintype = 28;</code>
     */
    private void setPDrivetraintypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pDrivetraintype_ = value.toStringUtf8();
    }

    public static final int P_MATCHSTRATEGY_FIELD_NUMBER = 29;
    private java.lang.String pMatchStrategy_;
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    public java.lang.String getPMatchStrategy() {
      return pMatchStrategy_;
    }
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    public com.google.protobuf.ByteString
        getPMatchStrategyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pMatchStrategy_);
    }
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    private void setPMatchStrategy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pMatchStrategy_ = value;
    }
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    private void clearPMatchStrategy() {
      
      pMatchStrategy_ = getDefaultInstance().getPMatchStrategy();
    }
    /**
     * <code>optional string p_matchStrategy = 29;</code>
     */
    private void setPMatchStrategyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pMatchStrategy_ = value.toStringUtf8();
    }

    public static final int P_ROBOTSTRENGTHS_FIELD_NUMBER = 30;
    private java.lang.String pRobotStrengths_;
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    public java.lang.String getPRobotStrengths() {
      return pRobotStrengths_;
    }
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    public com.google.protobuf.ByteString
        getPRobotStrengthsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pRobotStrengths_);
    }
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    private void setPRobotStrengths(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pRobotStrengths_ = value;
    }
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    private void clearPRobotStrengths() {
      
      pRobotStrengths_ = getDefaultInstance().getPRobotStrengths();
    }
    /**
     * <code>optional string p_robotStrengths = 30;</code>
     */
    private void setPRobotStrengthsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pRobotStrengths_ = value.toStringUtf8();
    }

    public static final int P_ROBOTWEAKNESSES_FIELD_NUMBER = 31;
    private java.lang.String pRobotWeaknesses_;
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    public java.lang.String getPRobotWeaknesses() {
      return pRobotWeaknesses_;
    }
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    public com.google.protobuf.ByteString
        getPRobotWeaknessesBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pRobotWeaknesses_);
    }
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    private void setPRobotWeaknesses(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pRobotWeaknesses_ = value;
    }
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    private void clearPRobotWeaknesses() {
      
      pRobotWeaknesses_ = getDefaultInstance().getPRobotWeaknesses();
    }
    /**
     * <code>optional string p_robotWeaknesses = 31;</code>
     */
    private void setPRobotWeaknessesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pRobotWeaknesses_ = value.toStringUtf8();
    }

    public static final int P_OTHERCOMMENTS_FIELD_NUMBER = 32;
    private java.lang.String pOtherComments_;
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    public java.lang.String getPOtherComments() {
      return pOtherComments_;
    }
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    public com.google.protobuf.ByteString
        getPOtherCommentsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pOtherComments_);
    }
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    private void setPOtherComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pOtherComments_ = value;
    }
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    private void clearPOtherComments() {
      
      pOtherComments_ = getDefaultInstance().getPOtherComments();
    }
    /**
     * <code>optional string p_otherComments = 32;</code>
     */
    private void setPOtherCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pOtherComments_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!password_.isEmpty()) {
        output.writeString(1, getPassword());
      }
      if (!eventCode_.isEmpty()) {
        output.writeString(2, getEventCode());
      }
      if (!scoutType_.isEmpty()) {
        output.writeString(3, getScoutType());
      }
      if (teamNumber_ != 0) {
        output.writeInt32(4, teamNumber_);
      }
      if (mMatchNumber_ != 0) {
        output.writeInt32(5, mMatchNumber_);
      }
      if (!mMatchType_.isEmpty()) {
        output.writeString(6, getMMatchType());
      }
      if (!mAllianceColor_.isEmpty()) {
        output.writeString(7, getMAllianceColor());
      }
      if (!mAutoGearStrategy_.isEmpty()) {
        output.writeString(8, getMAutoGearStrategy());
      }
      if (mAutoLowShots_ != 0) {
        output.writeInt32(9, mAutoLowShots_);
      }
      if (mAutoHighShots_ != 0) {
        output.writeInt32(10, mAutoHighShots_);
      }
      if (mAutoPercentShotsMissed_ != 0) {
        output.writeInt32(11, mAutoPercentShotsMissed_);
      }
      if (mAutoCrossedBaseline_ != false) {
        output.writeBool(12, mAutoCrossedBaseline_);
      }
      if (mTeleGearsPlaced_ != 0) {
        output.writeInt32(13, mTeleGearsPlaced_);
      }
      if (mTeleLowShots_ != 0) {
        output.writeInt32(14, mTeleLowShots_);
      }
      if (mTeleHighShots_ != 0) {
        output.writeInt32(15, mTeleHighShots_);
      }
      if (!mTelePercentShotsMissed_.isEmpty()) {
        output.writeString(16, getMTelePercentShotsMissed());
      }
      if (mTeleRotorsSpinning_ != 0) {
        output.writeInt32(17, mTeleRotorsSpinning_);
      }
      if (!mTeleBallRetrievalMethod_.isEmpty()) {
        output.writeString(18, getMTeleBallRetrievalMethod());
      }
      if (!mTeleRobotClimbStatus_.isEmpty()) {
        output.writeString(19, getMTeleRobotClimbStatus());
      }
      if (mTeleAirshipReadyForTakeoff_ != false) {
        output.writeBool(20, mTeleAirshipReadyForTakeoff_);
      }
      if (!mComments_.isEmpty()) {
        output.writeString(21, getMComments());
      }
      if (!mOverallStrategy_.isEmpty()) {
        output.writeString(22, getMOverallStrategy());
      }
      if (mRedMatchPoints_ != 0) {
        output.writeInt32(23, mRedMatchPoints_);
      }
      if (mBlueMatchPoints_ != 0) {
        output.writeInt32(24, mBlueMatchPoints_);
      }
      if (mRedRankingPoints_ != 0) {
        output.writeInt32(25, mRedRankingPoints_);
      }
      if (mBlueRankingPoints_ != 0) {
        output.writeInt32(26, mBlueRankingPoints_);
      }
      if (!pTeamName_.isEmpty()) {
        output.writeString(27, getPTeamName());
      }
      if (!pDrivetraintype_.isEmpty()) {
        output.writeString(28, getPDrivetraintype());
      }
      if (!pMatchStrategy_.isEmpty()) {
        output.writeString(29, getPMatchStrategy());
      }
      if (!pRobotStrengths_.isEmpty()) {
        output.writeString(30, getPRobotStrengths());
      }
      if (!pRobotWeaknesses_.isEmpty()) {
        output.writeString(31, getPRobotWeaknesses());
      }
      if (!pOtherComments_.isEmpty()) {
        output.writeString(32, getPOtherComments());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPassword());
      }
      if (!eventCode_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEventCode());
      }
      if (!scoutType_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getScoutType());
      }
      if (teamNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, teamNumber_);
      }
      if (mMatchNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mMatchNumber_);
      }
      if (!mMatchType_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getMMatchType());
      }
      if (!mAllianceColor_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getMAllianceColor());
      }
      if (!mAutoGearStrategy_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getMAutoGearStrategy());
      }
      if (mAutoLowShots_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, mAutoLowShots_);
      }
      if (mAutoHighShots_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, mAutoHighShots_);
      }
      if (mAutoPercentShotsMissed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, mAutoPercentShotsMissed_);
      }
      if (mAutoCrossedBaseline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, mAutoCrossedBaseline_);
      }
      if (mTeleGearsPlaced_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, mTeleGearsPlaced_);
      }
      if (mTeleLowShots_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, mTeleLowShots_);
      }
      if (mTeleHighShots_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, mTeleHighShots_);
      }
      if (!mTelePercentShotsMissed_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(16, getMTelePercentShotsMissed());
      }
      if (mTeleRotorsSpinning_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, mTeleRotorsSpinning_);
      }
      if (!mTeleBallRetrievalMethod_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(18, getMTeleBallRetrievalMethod());
      }
      if (!mTeleRobotClimbStatus_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(19, getMTeleRobotClimbStatus());
      }
      if (mTeleAirshipReadyForTakeoff_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, mTeleAirshipReadyForTakeoff_);
      }
      if (!mComments_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(21, getMComments());
      }
      if (!mOverallStrategy_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(22, getMOverallStrategy());
      }
      if (mRedMatchPoints_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, mRedMatchPoints_);
      }
      if (mBlueMatchPoints_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(24, mBlueMatchPoints_);
      }
      if (mRedRankingPoints_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, mRedRankingPoints_);
      }
      if (mBlueRankingPoints_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(26, mBlueRankingPoints_);
      }
      if (!pTeamName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(27, getPTeamName());
      }
      if (!pDrivetraintype_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(28, getPDrivetraintype());
      }
      if (!pMatchStrategy_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(29, getPMatchStrategy());
      }
      if (!pRobotStrengths_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(30, getPRobotStrengths());
      }
      if (!pRobotWeaknesses_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(31, getPRobotWeaknesses());
      }
      if (!pOtherComments_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(32, getPOtherComments());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Scoutingdata.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Scoutingdata.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Scoutingdata.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Scoutingdata.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Scoutingdata.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Scoutingdata.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Scoutingdata.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Scoutingdata.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Scoutingdata.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Scoutingdata.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Scoutingdata.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Scoutingdata.Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
        Scoutingdata.EventOrBuilder {
      // Construct using Scoutingdata.Event.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string password = 1;</code>
       */
      public java.lang.String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>optional string eventCode = 2;</code>
       */
      public java.lang.String getEventCode() {
        return instance.getEventCode();
      }
      /**
       * <code>optional string eventCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEventCodeBytes() {
        return instance.getEventCodeBytes();
      }
      /**
       * <code>optional string eventCode = 2;</code>
       */
      public Builder setEventCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setEventCode(value);
        return this;
      }
      /**
       * <code>optional string eventCode = 2;</code>
       */
      public Builder clearEventCode() {
        copyOnWrite();
        instance.clearEventCode();
        return this;
      }
      /**
       * <code>optional string eventCode = 2;</code>
       */
      public Builder setEventCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEventCodeBytes(value);
        return this;
      }

      /**
       * <code>optional string scoutType = 3;</code>
       */
      public java.lang.String getScoutType() {
        return instance.getScoutType();
      }
      /**
       * <code>optional string scoutType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getScoutTypeBytes() {
        return instance.getScoutTypeBytes();
      }
      /**
       * <code>optional string scoutType = 3;</code>
       */
      public Builder setScoutType(
          java.lang.String value) {
        copyOnWrite();
        instance.setScoutType(value);
        return this;
      }
      /**
       * <code>optional string scoutType = 3;</code>
       */
      public Builder clearScoutType() {
        copyOnWrite();
        instance.clearScoutType();
        return this;
      }
      /**
       * <code>optional string scoutType = 3;</code>
       */
      public Builder setScoutTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setScoutTypeBytes(value);
        return this;
      }

      /**
       * <code>optional int32 teamNumber = 4;</code>
       */
      public int getTeamNumber() {
        return instance.getTeamNumber();
      }
      /**
       * <code>optional int32 teamNumber = 4;</code>
       */
      public Builder setTeamNumber(int value) {
        copyOnWrite();
        instance.setTeamNumber(value);
        return this;
      }
      /**
       * <code>optional int32 teamNumber = 4;</code>
       */
      public Builder clearTeamNumber() {
        copyOnWrite();
        instance.clearTeamNumber();
        return this;
      }

      /**
       * <code>optional int32 m_matchNumber = 5;</code>
       */
      public int getMMatchNumber() {
        return instance.getMMatchNumber();
      }
      /**
       * <code>optional int32 m_matchNumber = 5;</code>
       */
      public Builder setMMatchNumber(int value) {
        copyOnWrite();
        instance.setMMatchNumber(value);
        return this;
      }
      /**
       * <code>optional int32 m_matchNumber = 5;</code>
       */
      public Builder clearMMatchNumber() {
        copyOnWrite();
        instance.clearMMatchNumber();
        return this;
      }

      /**
       * <code>optional string m_matchType = 6;</code>
       */
      public java.lang.String getMMatchType() {
        return instance.getMMatchType();
      }
      /**
       * <code>optional string m_matchType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMMatchTypeBytes() {
        return instance.getMMatchTypeBytes();
      }
      /**
       * <code>optional string m_matchType = 6;</code>
       */
      public Builder setMMatchType(
          java.lang.String value) {
        copyOnWrite();
        instance.setMMatchType(value);
        return this;
      }
      /**
       * <code>optional string m_matchType = 6;</code>
       */
      public Builder clearMMatchType() {
        copyOnWrite();
        instance.clearMMatchType();
        return this;
      }
      /**
       * <code>optional string m_matchType = 6;</code>
       */
      public Builder setMMatchTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMMatchTypeBytes(value);
        return this;
      }

      /**
       * <code>optional string m_allianceColor = 7;</code>
       */
      public java.lang.String getMAllianceColor() {
        return instance.getMAllianceColor();
      }
      /**
       * <code>optional string m_allianceColor = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMAllianceColorBytes() {
        return instance.getMAllianceColorBytes();
      }
      /**
       * <code>optional string m_allianceColor = 7;</code>
       */
      public Builder setMAllianceColor(
          java.lang.String value) {
        copyOnWrite();
        instance.setMAllianceColor(value);
        return this;
      }
      /**
       * <code>optional string m_allianceColor = 7;</code>
       */
      public Builder clearMAllianceColor() {
        copyOnWrite();
        instance.clearMAllianceColor();
        return this;
      }
      /**
       * <code>optional string m_allianceColor = 7;</code>
       */
      public Builder setMAllianceColorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMAllianceColorBytes(value);
        return this;
      }

      /**
       * <code>optional string m_auto_gearStrategy = 8;</code>
       */
      public java.lang.String getMAutoGearStrategy() {
        return instance.getMAutoGearStrategy();
      }
      /**
       * <code>optional string m_auto_gearStrategy = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMAutoGearStrategyBytes() {
        return instance.getMAutoGearStrategyBytes();
      }
      /**
       * <code>optional string m_auto_gearStrategy = 8;</code>
       */
      public Builder setMAutoGearStrategy(
          java.lang.String value) {
        copyOnWrite();
        instance.setMAutoGearStrategy(value);
        return this;
      }
      /**
       * <code>optional string m_auto_gearStrategy = 8;</code>
       */
      public Builder clearMAutoGearStrategy() {
        copyOnWrite();
        instance.clearMAutoGearStrategy();
        return this;
      }
      /**
       * <code>optional string m_auto_gearStrategy = 8;</code>
       */
      public Builder setMAutoGearStrategyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMAutoGearStrategyBytes(value);
        return this;
      }

      /**
       * <code>optional int32 m_auto_lowShots = 9;</code>
       */
      public int getMAutoLowShots() {
        return instance.getMAutoLowShots();
      }
      /**
       * <code>optional int32 m_auto_lowShots = 9;</code>
       */
      public Builder setMAutoLowShots(int value) {
        copyOnWrite();
        instance.setMAutoLowShots(value);
        return this;
      }
      /**
       * <code>optional int32 m_auto_lowShots = 9;</code>
       */
      public Builder clearMAutoLowShots() {
        copyOnWrite();
        instance.clearMAutoLowShots();
        return this;
      }

      /**
       * <code>optional int32 m_auto_highShots = 10;</code>
       */
      public int getMAutoHighShots() {
        return instance.getMAutoHighShots();
      }
      /**
       * <code>optional int32 m_auto_highShots = 10;</code>
       */
      public Builder setMAutoHighShots(int value) {
        copyOnWrite();
        instance.setMAutoHighShots(value);
        return this;
      }
      /**
       * <code>optional int32 m_auto_highShots = 10;</code>
       */
      public Builder clearMAutoHighShots() {
        copyOnWrite();
        instance.clearMAutoHighShots();
        return this;
      }

      /**
       * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
       */
      public int getMAutoPercentShotsMissed() {
        return instance.getMAutoPercentShotsMissed();
      }
      /**
       * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
       */
      public Builder setMAutoPercentShotsMissed(int value) {
        copyOnWrite();
        instance.setMAutoPercentShotsMissed(value);
        return this;
      }
      /**
       * <code>optional int32 m_auto_percentShotsMissed = 11;</code>
       */
      public Builder clearMAutoPercentShotsMissed() {
        copyOnWrite();
        instance.clearMAutoPercentShotsMissed();
        return this;
      }

      /**
       * <code>optional bool m_auto_crossedBaseline = 12;</code>
       */
      public boolean getMAutoCrossedBaseline() {
        return instance.getMAutoCrossedBaseline();
      }
      /**
       * <code>optional bool m_auto_crossedBaseline = 12;</code>
       */
      public Builder setMAutoCrossedBaseline(boolean value) {
        copyOnWrite();
        instance.setMAutoCrossedBaseline(value);
        return this;
      }
      /**
       * <code>optional bool m_auto_crossedBaseline = 12;</code>
       */
      public Builder clearMAutoCrossedBaseline() {
        copyOnWrite();
        instance.clearMAutoCrossedBaseline();
        return this;
      }

      /**
       * <code>optional int32 m_tele_gearsPlaced = 13;</code>
       */
      public int getMTeleGearsPlaced() {
        return instance.getMTeleGearsPlaced();
      }
      /**
       * <code>optional int32 m_tele_gearsPlaced = 13;</code>
       */
      public Builder setMTeleGearsPlaced(int value) {
        copyOnWrite();
        instance.setMTeleGearsPlaced(value);
        return this;
      }
      /**
       * <code>optional int32 m_tele_gearsPlaced = 13;</code>
       */
      public Builder clearMTeleGearsPlaced() {
        copyOnWrite();
        instance.clearMTeleGearsPlaced();
        return this;
      }

      /**
       * <code>optional int32 m_tele_lowShots = 14;</code>
       */
      public int getMTeleLowShots() {
        return instance.getMTeleLowShots();
      }
      /**
       * <code>optional int32 m_tele_lowShots = 14;</code>
       */
      public Builder setMTeleLowShots(int value) {
        copyOnWrite();
        instance.setMTeleLowShots(value);
        return this;
      }
      /**
       * <code>optional int32 m_tele_lowShots = 14;</code>
       */
      public Builder clearMTeleLowShots() {
        copyOnWrite();
        instance.clearMTeleLowShots();
        return this;
      }

      /**
       * <code>optional int32 m_tele_highShots = 15;</code>
       */
      public int getMTeleHighShots() {
        return instance.getMTeleHighShots();
      }
      /**
       * <code>optional int32 m_tele_highShots = 15;</code>
       */
      public Builder setMTeleHighShots(int value) {
        copyOnWrite();
        instance.setMTeleHighShots(value);
        return this;
      }
      /**
       * <code>optional int32 m_tele_highShots = 15;</code>
       */
      public Builder clearMTeleHighShots() {
        copyOnWrite();
        instance.clearMTeleHighShots();
        return this;
      }

      /**
       * <code>optional string m_tele_percentShotsMissed = 16;</code>
       */
      public java.lang.String getMTelePercentShotsMissed() {
        return instance.getMTelePercentShotsMissed();
      }
      /**
       * <code>optional string m_tele_percentShotsMissed = 16;</code>
       */
      public com.google.protobuf.ByteString
          getMTelePercentShotsMissedBytes() {
        return instance.getMTelePercentShotsMissedBytes();
      }
      /**
       * <code>optional string m_tele_percentShotsMissed = 16;</code>
       */
      public Builder setMTelePercentShotsMissed(
          java.lang.String value) {
        copyOnWrite();
        instance.setMTelePercentShotsMissed(value);
        return this;
      }
      /**
       * <code>optional string m_tele_percentShotsMissed = 16;</code>
       */
      public Builder clearMTelePercentShotsMissed() {
        copyOnWrite();
        instance.clearMTelePercentShotsMissed();
        return this;
      }
      /**
       * <code>optional string m_tele_percentShotsMissed = 16;</code>
       */
      public Builder setMTelePercentShotsMissedBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMTelePercentShotsMissedBytes(value);
        return this;
      }

      /**
       * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
       */
      public int getMTeleRotorsSpinning() {
        return instance.getMTeleRotorsSpinning();
      }
      /**
       * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
       */
      public Builder setMTeleRotorsSpinning(int value) {
        copyOnWrite();
        instance.setMTeleRotorsSpinning(value);
        return this;
      }
      /**
       * <code>optional int32 m_tele_rotorsSpinning = 17;</code>
       */
      public Builder clearMTeleRotorsSpinning() {
        copyOnWrite();
        instance.clearMTeleRotorsSpinning();
        return this;
      }

      /**
       * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
       */
      public java.lang.String getMTeleBallRetrievalMethod() {
        return instance.getMTeleBallRetrievalMethod();
      }
      /**
       * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
       */
      public com.google.protobuf.ByteString
          getMTeleBallRetrievalMethodBytes() {
        return instance.getMTeleBallRetrievalMethodBytes();
      }
      /**
       * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
       */
      public Builder setMTeleBallRetrievalMethod(
          java.lang.String value) {
        copyOnWrite();
        instance.setMTeleBallRetrievalMethod(value);
        return this;
      }
      /**
       * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
       */
      public Builder clearMTeleBallRetrievalMethod() {
        copyOnWrite();
        instance.clearMTeleBallRetrievalMethod();
        return this;
      }
      /**
       * <code>optional string m_tele_ballRetrievalMethod = 18;</code>
       */
      public Builder setMTeleBallRetrievalMethodBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMTeleBallRetrievalMethodBytes(value);
        return this;
      }

      /**
       * <code>optional string m_tele_robotClimbStatus = 19;</code>
       */
      public java.lang.String getMTeleRobotClimbStatus() {
        return instance.getMTeleRobotClimbStatus();
      }
      /**
       * <code>optional string m_tele_robotClimbStatus = 19;</code>
       */
      public com.google.protobuf.ByteString
          getMTeleRobotClimbStatusBytes() {
        return instance.getMTeleRobotClimbStatusBytes();
      }
      /**
       * <code>optional string m_tele_robotClimbStatus = 19;</code>
       */
      public Builder setMTeleRobotClimbStatus(
          java.lang.String value) {
        copyOnWrite();
        instance.setMTeleRobotClimbStatus(value);
        return this;
      }
      /**
       * <code>optional string m_tele_robotClimbStatus = 19;</code>
       */
      public Builder clearMTeleRobotClimbStatus() {
        copyOnWrite();
        instance.clearMTeleRobotClimbStatus();
        return this;
      }
      /**
       * <code>optional string m_tele_robotClimbStatus = 19;</code>
       */
      public Builder setMTeleRobotClimbStatusBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMTeleRobotClimbStatusBytes(value);
        return this;
      }

      /**
       * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
       */
      public boolean getMTeleAirshipReadyForTakeoff() {
        return instance.getMTeleAirshipReadyForTakeoff();
      }
      /**
       * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
       */
      public Builder setMTeleAirshipReadyForTakeoff(boolean value) {
        copyOnWrite();
        instance.setMTeleAirshipReadyForTakeoff(value);
        return this;
      }
      /**
       * <code>optional bool m_tele_airshipReadyForTakeoff = 20;</code>
       */
      public Builder clearMTeleAirshipReadyForTakeoff() {
        copyOnWrite();
        instance.clearMTeleAirshipReadyForTakeoff();
        return this;
      }

      /**
       * <code>optional string m_comments = 21;</code>
       */
      public java.lang.String getMComments() {
        return instance.getMComments();
      }
      /**
       * <code>optional string m_comments = 21;</code>
       */
      public com.google.protobuf.ByteString
          getMCommentsBytes() {
        return instance.getMCommentsBytes();
      }
      /**
       * <code>optional string m_comments = 21;</code>
       */
      public Builder setMComments(
          java.lang.String value) {
        copyOnWrite();
        instance.setMComments(value);
        return this;
      }
      /**
       * <code>optional string m_comments = 21;</code>
       */
      public Builder clearMComments() {
        copyOnWrite();
        instance.clearMComments();
        return this;
      }
      /**
       * <code>optional string m_comments = 21;</code>
       */
      public Builder setMCommentsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMCommentsBytes(value);
        return this;
      }

      /**
       * <code>optional string m_overallStrategy = 22;</code>
       */
      public java.lang.String getMOverallStrategy() {
        return instance.getMOverallStrategy();
      }
      /**
       * <code>optional string m_overallStrategy = 22;</code>
       */
      public com.google.protobuf.ByteString
          getMOverallStrategyBytes() {
        return instance.getMOverallStrategyBytes();
      }
      /**
       * <code>optional string m_overallStrategy = 22;</code>
       */
      public Builder setMOverallStrategy(
          java.lang.String value) {
        copyOnWrite();
        instance.setMOverallStrategy(value);
        return this;
      }
      /**
       * <code>optional string m_overallStrategy = 22;</code>
       */
      public Builder clearMOverallStrategy() {
        copyOnWrite();
        instance.clearMOverallStrategy();
        return this;
      }
      /**
       * <code>optional string m_overallStrategy = 22;</code>
       */
      public Builder setMOverallStrategyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMOverallStrategyBytes(value);
        return this;
      }

      /**
       * <code>optional int32 m_redMatchPoints = 23;</code>
       */
      public int getMRedMatchPoints() {
        return instance.getMRedMatchPoints();
      }
      /**
       * <code>optional int32 m_redMatchPoints = 23;</code>
       */
      public Builder setMRedMatchPoints(int value) {
        copyOnWrite();
        instance.setMRedMatchPoints(value);
        return this;
      }
      /**
       * <code>optional int32 m_redMatchPoints = 23;</code>
       */
      public Builder clearMRedMatchPoints() {
        copyOnWrite();
        instance.clearMRedMatchPoints();
        return this;
      }

      /**
       * <code>optional int32 m_blueMatchPoints = 24;</code>
       */
      public int getMBlueMatchPoints() {
        return instance.getMBlueMatchPoints();
      }
      /**
       * <code>optional int32 m_blueMatchPoints = 24;</code>
       */
      public Builder setMBlueMatchPoints(int value) {
        copyOnWrite();
        instance.setMBlueMatchPoints(value);
        return this;
      }
      /**
       * <code>optional int32 m_blueMatchPoints = 24;</code>
       */
      public Builder clearMBlueMatchPoints() {
        copyOnWrite();
        instance.clearMBlueMatchPoints();
        return this;
      }

      /**
       * <code>optional int32 m_redRankingPoints = 25;</code>
       */
      public int getMRedRankingPoints() {
        return instance.getMRedRankingPoints();
      }
      /**
       * <code>optional int32 m_redRankingPoints = 25;</code>
       */
      public Builder setMRedRankingPoints(int value) {
        copyOnWrite();
        instance.setMRedRankingPoints(value);
        return this;
      }
      /**
       * <code>optional int32 m_redRankingPoints = 25;</code>
       */
      public Builder clearMRedRankingPoints() {
        copyOnWrite();
        instance.clearMRedRankingPoints();
        return this;
      }

      /**
       * <code>optional int32 m_blueRankingPoints = 26;</code>
       */
      public int getMBlueRankingPoints() {
        return instance.getMBlueRankingPoints();
      }
      /**
       * <code>optional int32 m_blueRankingPoints = 26;</code>
       */
      public Builder setMBlueRankingPoints(int value) {
        copyOnWrite();
        instance.setMBlueRankingPoints(value);
        return this;
      }
      /**
       * <code>optional int32 m_blueRankingPoints = 26;</code>
       */
      public Builder clearMBlueRankingPoints() {
        copyOnWrite();
        instance.clearMBlueRankingPoints();
        return this;
      }

      /**
       * <code>optional string p_teamName = 27;</code>
       */
      public java.lang.String getPTeamName() {
        return instance.getPTeamName();
      }
      /**
       * <code>optional string p_teamName = 27;</code>
       */
      public com.google.protobuf.ByteString
          getPTeamNameBytes() {
        return instance.getPTeamNameBytes();
      }
      /**
       * <code>optional string p_teamName = 27;</code>
       */
      public Builder setPTeamName(
          java.lang.String value) {
        copyOnWrite();
        instance.setPTeamName(value);
        return this;
      }
      /**
       * <code>optional string p_teamName = 27;</code>
       */
      public Builder clearPTeamName() {
        copyOnWrite();
        instance.clearPTeamName();
        return this;
      }
      /**
       * <code>optional string p_teamName = 27;</code>
       */
      public Builder setPTeamNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPTeamNameBytes(value);
        return this;
      }

      /**
       * <code>optional string p_drivetraintype = 28;</code>
       */
      public java.lang.String getPDrivetraintype() {
        return instance.getPDrivetraintype();
      }
      /**
       * <code>optional string p_drivetraintype = 28;</code>
       */
      public com.google.protobuf.ByteString
          getPDrivetraintypeBytes() {
        return instance.getPDrivetraintypeBytes();
      }
      /**
       * <code>optional string p_drivetraintype = 28;</code>
       */
      public Builder setPDrivetraintype(
          java.lang.String value) {
        copyOnWrite();
        instance.setPDrivetraintype(value);
        return this;
      }
      /**
       * <code>optional string p_drivetraintype = 28;</code>
       */
      public Builder clearPDrivetraintype() {
        copyOnWrite();
        instance.clearPDrivetraintype();
        return this;
      }
      /**
       * <code>optional string p_drivetraintype = 28;</code>
       */
      public Builder setPDrivetraintypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPDrivetraintypeBytes(value);
        return this;
      }

      /**
       * <code>optional string p_matchStrategy = 29;</code>
       */
      public java.lang.String getPMatchStrategy() {
        return instance.getPMatchStrategy();
      }
      /**
       * <code>optional string p_matchStrategy = 29;</code>
       */
      public com.google.protobuf.ByteString
          getPMatchStrategyBytes() {
        return instance.getPMatchStrategyBytes();
      }
      /**
       * <code>optional string p_matchStrategy = 29;</code>
       */
      public Builder setPMatchStrategy(
          java.lang.String value) {
        copyOnWrite();
        instance.setPMatchStrategy(value);
        return this;
      }
      /**
       * <code>optional string p_matchStrategy = 29;</code>
       */
      public Builder clearPMatchStrategy() {
        copyOnWrite();
        instance.clearPMatchStrategy();
        return this;
      }
      /**
       * <code>optional string p_matchStrategy = 29;</code>
       */
      public Builder setPMatchStrategyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPMatchStrategyBytes(value);
        return this;
      }

      /**
       * <code>optional string p_robotStrengths = 30;</code>
       */
      public java.lang.String getPRobotStrengths() {
        return instance.getPRobotStrengths();
      }
      /**
       * <code>optional string p_robotStrengths = 30;</code>
       */
      public com.google.protobuf.ByteString
          getPRobotStrengthsBytes() {
        return instance.getPRobotStrengthsBytes();
      }
      /**
       * <code>optional string p_robotStrengths = 30;</code>
       */
      public Builder setPRobotStrengths(
          java.lang.String value) {
        copyOnWrite();
        instance.setPRobotStrengths(value);
        return this;
      }
      /**
       * <code>optional string p_robotStrengths = 30;</code>
       */
      public Builder clearPRobotStrengths() {
        copyOnWrite();
        instance.clearPRobotStrengths();
        return this;
      }
      /**
       * <code>optional string p_robotStrengths = 30;</code>
       */
      public Builder setPRobotStrengthsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPRobotStrengthsBytes(value);
        return this;
      }

      /**
       * <code>optional string p_robotWeaknesses = 31;</code>
       */
      public java.lang.String getPRobotWeaknesses() {
        return instance.getPRobotWeaknesses();
      }
      /**
       * <code>optional string p_robotWeaknesses = 31;</code>
       */
      public com.google.protobuf.ByteString
          getPRobotWeaknessesBytes() {
        return instance.getPRobotWeaknessesBytes();
      }
      /**
       * <code>optional string p_robotWeaknesses = 31;</code>
       */
      public Builder setPRobotWeaknesses(
          java.lang.String value) {
        copyOnWrite();
        instance.setPRobotWeaknesses(value);
        return this;
      }
      /**
       * <code>optional string p_robotWeaknesses = 31;</code>
       */
      public Builder clearPRobotWeaknesses() {
        copyOnWrite();
        instance.clearPRobotWeaknesses();
        return this;
      }
      /**
       * <code>optional string p_robotWeaknesses = 31;</code>
       */
      public Builder setPRobotWeaknessesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPRobotWeaknessesBytes(value);
        return this;
      }

      /**
       * <code>optional string p_otherComments = 32;</code>
       */
      public java.lang.String getPOtherComments() {
        return instance.getPOtherComments();
      }
      /**
       * <code>optional string p_otherComments = 32;</code>
       */
      public com.google.protobuf.ByteString
          getPOtherCommentsBytes() {
        return instance.getPOtherCommentsBytes();
      }
      /**
       * <code>optional string p_otherComments = 32;</code>
       */
      public Builder setPOtherComments(
          java.lang.String value) {
        copyOnWrite();
        instance.setPOtherComments(value);
        return this;
      }
      /**
       * <code>optional string p_otherComments = 32;</code>
       */
      public Builder clearPOtherComments() {
        copyOnWrite();
        instance.clearPOtherComments();
        return this;
      }
      /**
       * <code>optional string p_otherComments = 32;</code>
       */
      public Builder setPOtherCommentsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPOtherCommentsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Event)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Scoutingdata.Event();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Scoutingdata.Event other = (Scoutingdata.Event) arg1;
          password_ = visitor.visitString(!password_.isEmpty(), password_,
              !other.password_.isEmpty(), other.password_);
          eventCode_ = visitor.visitString(!eventCode_.isEmpty(), eventCode_,
              !other.eventCode_.isEmpty(), other.eventCode_);
          scoutType_ = visitor.visitString(!scoutType_.isEmpty(), scoutType_,
              !other.scoutType_.isEmpty(), other.scoutType_);
          teamNumber_ = visitor.visitInt(teamNumber_ != 0, teamNumber_,
              other.teamNumber_ != 0, other.teamNumber_);
          mMatchNumber_ = visitor.visitInt(mMatchNumber_ != 0, mMatchNumber_,
              other.mMatchNumber_ != 0, other.mMatchNumber_);
          mMatchType_ = visitor.visitString(!mMatchType_.isEmpty(), mMatchType_,
              !other.mMatchType_.isEmpty(), other.mMatchType_);
          mAllianceColor_ = visitor.visitString(!mAllianceColor_.isEmpty(), mAllianceColor_,
              !other.mAllianceColor_.isEmpty(), other.mAllianceColor_);
          mAutoGearStrategy_ = visitor.visitString(!mAutoGearStrategy_.isEmpty(), mAutoGearStrategy_,
              !other.mAutoGearStrategy_.isEmpty(), other.mAutoGearStrategy_);
          mAutoLowShots_ = visitor.visitInt(mAutoLowShots_ != 0, mAutoLowShots_,
              other.mAutoLowShots_ != 0, other.mAutoLowShots_);
          mAutoHighShots_ = visitor.visitInt(mAutoHighShots_ != 0, mAutoHighShots_,
              other.mAutoHighShots_ != 0, other.mAutoHighShots_);
          mAutoPercentShotsMissed_ = visitor.visitInt(mAutoPercentShotsMissed_ != 0, mAutoPercentShotsMissed_,
              other.mAutoPercentShotsMissed_ != 0, other.mAutoPercentShotsMissed_);
          mAutoCrossedBaseline_ = visitor.visitBoolean(mAutoCrossedBaseline_ != false, mAutoCrossedBaseline_,
              other.mAutoCrossedBaseline_ != false, other.mAutoCrossedBaseline_);
          mTeleGearsPlaced_ = visitor.visitInt(mTeleGearsPlaced_ != 0, mTeleGearsPlaced_,
              other.mTeleGearsPlaced_ != 0, other.mTeleGearsPlaced_);
          mTeleLowShots_ = visitor.visitInt(mTeleLowShots_ != 0, mTeleLowShots_,
              other.mTeleLowShots_ != 0, other.mTeleLowShots_);
          mTeleHighShots_ = visitor.visitInt(mTeleHighShots_ != 0, mTeleHighShots_,
              other.mTeleHighShots_ != 0, other.mTeleHighShots_);
          mTelePercentShotsMissed_ = visitor.visitString(!mTelePercentShotsMissed_.isEmpty(), mTelePercentShotsMissed_,
              !other.mTelePercentShotsMissed_.isEmpty(), other.mTelePercentShotsMissed_);
          mTeleRotorsSpinning_ = visitor.visitInt(mTeleRotorsSpinning_ != 0, mTeleRotorsSpinning_,
              other.mTeleRotorsSpinning_ != 0, other.mTeleRotorsSpinning_);
          mTeleBallRetrievalMethod_ = visitor.visitString(!mTeleBallRetrievalMethod_.isEmpty(), mTeleBallRetrievalMethod_,
              !other.mTeleBallRetrievalMethod_.isEmpty(), other.mTeleBallRetrievalMethod_);
          mTeleRobotClimbStatus_ = visitor.visitString(!mTeleRobotClimbStatus_.isEmpty(), mTeleRobotClimbStatus_,
              !other.mTeleRobotClimbStatus_.isEmpty(), other.mTeleRobotClimbStatus_);
          mTeleAirshipReadyForTakeoff_ = visitor.visitBoolean(mTeleAirshipReadyForTakeoff_ != false, mTeleAirshipReadyForTakeoff_,
              other.mTeleAirshipReadyForTakeoff_ != false, other.mTeleAirshipReadyForTakeoff_);
          mComments_ = visitor.visitString(!mComments_.isEmpty(), mComments_,
              !other.mComments_.isEmpty(), other.mComments_);
          mOverallStrategy_ = visitor.visitString(!mOverallStrategy_.isEmpty(), mOverallStrategy_,
              !other.mOverallStrategy_.isEmpty(), other.mOverallStrategy_);
          mRedMatchPoints_ = visitor.visitInt(mRedMatchPoints_ != 0, mRedMatchPoints_,
              other.mRedMatchPoints_ != 0, other.mRedMatchPoints_);
          mBlueMatchPoints_ = visitor.visitInt(mBlueMatchPoints_ != 0, mBlueMatchPoints_,
              other.mBlueMatchPoints_ != 0, other.mBlueMatchPoints_);
          mRedRankingPoints_ = visitor.visitInt(mRedRankingPoints_ != 0, mRedRankingPoints_,
              other.mRedRankingPoints_ != 0, other.mRedRankingPoints_);
          mBlueRankingPoints_ = visitor.visitInt(mBlueRankingPoints_ != 0, mBlueRankingPoints_,
              other.mBlueRankingPoints_ != 0, other.mBlueRankingPoints_);
          pTeamName_ = visitor.visitString(!pTeamName_.isEmpty(), pTeamName_,
              !other.pTeamName_.isEmpty(), other.pTeamName_);
          pDrivetraintype_ = visitor.visitString(!pDrivetraintype_.isEmpty(), pDrivetraintype_,
              !other.pDrivetraintype_.isEmpty(), other.pDrivetraintype_);
          pMatchStrategy_ = visitor.visitString(!pMatchStrategy_.isEmpty(), pMatchStrategy_,
              !other.pMatchStrategy_.isEmpty(), other.pMatchStrategy_);
          pRobotStrengths_ = visitor.visitString(!pRobotStrengths_.isEmpty(), pRobotStrengths_,
              !other.pRobotStrengths_.isEmpty(), other.pRobotStrengths_);
          pRobotWeaknesses_ = visitor.visitString(!pRobotWeaknesses_.isEmpty(), pRobotWeaknesses_,
              !other.pRobotWeaknesses_.isEmpty(), other.pRobotWeaknesses_);
          pOtherComments_ = visitor.visitString(!pOtherComments_.isEmpty(), pOtherComments_,
              !other.pOtherComments_.isEmpty(), other.pOtherComments_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  password_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  eventCode_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  scoutType_ = s;
                  break;
                }
                case 32: {

                  teamNumber_ = input.readInt32();
                  break;
                }
                case 40: {

                  mMatchNumber_ = input.readInt32();
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  mMatchType_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  mAllianceColor_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  mAutoGearStrategy_ = s;
                  break;
                }
                case 72: {

                  mAutoLowShots_ = input.readInt32();
                  break;
                }
                case 80: {

                  mAutoHighShots_ = input.readInt32();
                  break;
                }
                case 88: {

                  mAutoPercentShotsMissed_ = input.readInt32();
                  break;
                }
                case 96: {

                  mAutoCrossedBaseline_ = input.readBool();
                  break;
                }
                case 104: {

                  mTeleGearsPlaced_ = input.readInt32();
                  break;
                }
                case 112: {

                  mTeleLowShots_ = input.readInt32();
                  break;
                }
                case 120: {

                  mTeleHighShots_ = input.readInt32();
                  break;
                }
                case 130: {
                  String s = input.readStringRequireUtf8();

                  mTelePercentShotsMissed_ = s;
                  break;
                }
                case 136: {

                  mTeleRotorsSpinning_ = input.readInt32();
                  break;
                }
                case 146: {
                  String s = input.readStringRequireUtf8();

                  mTeleBallRetrievalMethod_ = s;
                  break;
                }
                case 154: {
                  String s = input.readStringRequireUtf8();

                  mTeleRobotClimbStatus_ = s;
                  break;
                }
                case 160: {

                  mTeleAirshipReadyForTakeoff_ = input.readBool();
                  break;
                }
                case 170: {
                  String s = input.readStringRequireUtf8();

                  mComments_ = s;
                  break;
                }
                case 178: {
                  String s = input.readStringRequireUtf8();

                  mOverallStrategy_ = s;
                  break;
                }
                case 184: {

                  mRedMatchPoints_ = input.readInt32();
                  break;
                }
                case 192: {

                  mBlueMatchPoints_ = input.readInt32();
                  break;
                }
                case 200: {

                  mRedRankingPoints_ = input.readInt32();
                  break;
                }
                case 208: {

                  mBlueRankingPoints_ = input.readInt32();
                  break;
                }
                case 218: {
                  String s = input.readStringRequireUtf8();

                  pTeamName_ = s;
                  break;
                }
                case 226: {
                  String s = input.readStringRequireUtf8();

                  pDrivetraintype_ = s;
                  break;
                }
                case 234: {
                  String s = input.readStringRequireUtf8();

                  pMatchStrategy_ = s;
                  break;
                }
                case 242: {
                  String s = input.readStringRequireUtf8();

                  pRobotStrengths_ = s;
                  break;
                }
                case 250: {
                  String s = input.readStringRequireUtf8();

                  pRobotWeaknesses_ = s;
                  break;
                }
                case 258: {
                  String s = input.readStringRequireUtf8();

                  pOtherComments_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Scoutingdata.Event.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Event)
    private static final Scoutingdata.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Event();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Scoutingdata.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Event> PARSER;

    public static com.google.protobuf.Parser<Event> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
